### ISSUE TITLE
Expanding the simulation

### ISSUE THREAD

**Issue by Asdafers** [timmson/kanban-game#62]
Hi @timmson,
Are there any plans to add the ability to see the dice being rolled, plus maybe adding 'next' and 'back' buttons as an option on top of the continuous play that's currently there? Just to let people talk through what's happening on the board?

Implementing the whole game with events and card descriptions would be even better :)

**Comment by timmson** [comment]
Hi @Asdafers!
I appreciate any feedback regading to my projects!  If you look for a simulation of the getKanban game you can use this - http://www.kanbanboardgame.com/.
